// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThiagoViniciusOliveiraDeSouza.Models;

#nullable disable

namespace ThiagoViniciusOliveiraDeSouza.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20240510142638_CreateDb")]
    partial class CreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("ThiagoViniciusOliveiraDeSouza.Models.Folha", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ImpostoFgts")
                        .HasColumnType("REAL");

                    b.Property<double?>("ImpostoInss")
                        .HasColumnType("REAL");

                    b.Property<double?>("ImpostoIrrf")
                        .HasColumnType("REAL");

                    b.Property<int?>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Quantidade")
                        .HasColumnType("REAL");

                    b.Property<double?>("SalarioBruto")
                        .HasColumnType("REAL");

                    b.Property<double?>("SalarioLiquido")
                        .HasColumnType("REAL");

                    b.Property<double?>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId")
                        .IsUnique();

                    b.ToTable("Folha");
                });

            modelBuilder.Entity("ThiagoViniciusOliveiraDeSouza.Models.Funcionario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("ThiagoViniciusOliveiraDeSouza.Models.Folha", b =>
                {
                    b.HasOne("ThiagoViniciusOliveiraDeSouza.Models.Funcionario", null)
                        .WithOne("Folha")
                        .HasForeignKey("ThiagoViniciusOliveiraDeSouza.Models.Folha", "FuncionarioId");
                });

            modelBuilder.Entity("ThiagoViniciusOliveiraDeSouza.Models.Funcionario", b =>
                {
                    b.Navigation("Folha");
                });
#pragma warning restore 612, 618
        }
    }
}
